# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10.0

#: }}}

#: Scrollback {{{

scrollback_lines 5000

#: }}}

#: Color scheme {{{

# The basic colors
foreground              #cad3f5
background              #24273a
selection_foreground    #24273a
selection_background    #f4dbd6

# Cursor colors
cursor                  #f4dbd6
cursor_text_color       #24273a

# URL underline color when hovering with mouse
url_color               #f4dbd6

# Kitty window border colors
active_border_color     #b7bdf8
inactive_border_color   #6e738d
bell_border_color       #eed49f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181926
active_tab_background   #c6a0f6
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030
tab_bar_background      #181926

# Colors for marks (marked text in the terminal)
mark1_foreground #24273a
mark1_background #b7bdf8
mark2_foreground #24273a
mark2_background #c6a0f6
mark3_foreground #24273a
mark3_background #7dc4e4

# The 16 terminal colors

# black
color0 #494d64
color8 #5b6078

# red
color1 #ed8796
color9 #ed8796

# green
color2  #a6da95
color10 #a6da95

# yellow
color3  #eed49f
color11 #eed49f

# blue
color4  #8aadf4
color12 #8aadf4

# magenta
color5  #f5bde6
color13 #f5bde6

# cyan
color6  #8bd5ca
color14 #8bd5ca

# white
color7  #b8c0e0
color15 #a5adcb

#: }}}

#: Advanced {{{

confirm_os_window_close 0

# No confirmation for close windows (we are using tmux)

close_on_child_death no

#: Close the window when the child process (usually the shell) exits.
#: With the default value no, the terminal will remain open when the
#: child exits as long as there are still other processes outputting
#: to the terminal (for example disowned or backgrounded processes).
#: When enabled with yes, the window will close as soon as the child
#: process exits. Note that setting it to yes means that any
#: background processes still using the terminal can fail silently
#: because their stdout/stderr/stdin no longer work.

allow_remote_control no

#: Allow other programs to control kitty. If you turn this on, other
#: programs can control all aspects of kitty, including sending text
#: to kitty windows, opening new windows, closing windows, reading the
#: content of windows, etc. Note that this even works over SSH
#: connections. The default setting of no prevents any form of remote
#: control. The meaning of the various values are:

listen_on none

#: Listen to the specified socket for remote control connections. Note
#: that this will apply to all kitty instances. It can be overridden
#: by the kitty --listen-on command line option. For UNIX sockets,
#: such as unix:${TEMP}/mykitty or unix:@mykitty (on Linux).
#: Environment variables are expanded and relative paths are resolved
#: with respect to the temporary directory. If {kitty_pid} is present,
#: then it is replaced by the PID of the kitty process, otherwise the
#: PID of the kitty process is appended to the value, with a hyphen.
#: For TCP sockets such as tcp:localhost:0 a random port is always
#: used even if a non-zero port number is specified.  See the help for
#: kitty --listen-on for more details. Note that this will be ignored
#: unless allow_remote_control is set to either: yes, socket or
#: socket-only. Changing this option by reloading the config is not
#: supported.

#: }}}

